### ISSUE TITLE
Calendar briefly draws on load before hiding.

### ISSUE THREAD

**Issue by Nfinished** [eureka2/ab-datepicker#1]
The calendar header shows with 'Javascript must be enabled' displaying instead of the grid.

**Comment by nickgoodrow** [comment]
The quick way. Include a label that point to your input field
<label for="date">DatePicker</span></label>

**Comment by nickgoodrow** [comment]
`<label  for="date">DatePicker</label>`

**Comment by eureka2** [comment]
Fixed in release 2.1.8
