### ISSUE TITLE
Extend Calendar View

### ISSUE THREAD

**Issue by Snahendu** [eureka2/ab-datepicker#10]
How do I extend this calendar view to multiple months? say, I want to see two months or three months side by side.

**Comment by eureka2** [comment]
No, it's not possible for the moment, sorry!

**Comment by eureka2** [comment]
I suppose you want a multi-calendars view linked to the same input as jqueryui proposes does: https://jqueryui.com/resources/demos/datepicker/multiple-calendars.html
Note that you can not select a date with the keyboard.

But, ab-dapicker's main goal is accessibility, and I do not know how to make a three-month view accessible. How to navigate with keyboard between the different months? How do I tell the screen reader what month we are? W3C and WAI do not provide specifications for this.

If you have any answers to these questions, let me know.

Best regards

**Comment by eureka2** [comment]
closed due to non-response
