### ISSUE TITLE
Add Start Views for DOB

### ISSUE THREAD

**Issue by lordorica** [eureka2/ab-datepicker#11]
When input is a date of birth, it is convenient to start with the Year panel shown, then Month, followed by Day.

Thank you

**Comment by eureka2** [comment]
It's a very good idea, coming soon with the 'startView' option

**Comment by eureka2** [comment]
The 'startView' option is added !
use "startView: 'years'" for date of birth

**Comment by lordorica** [comment]
C'est formidable! Merci, thank you
