### ISSUE TITLE
Using public methods

### ISSUE THREAD

**Issue by stefanos-tsaklas** [eureka2/ab-datepicker#13]
Can you please clarify how the public methods can be used?

In the documentation you are mentioning this:
```
getDate
$('your date selector').datepicker('getDate');
Get the current Datepicker date object
```

But this throws an exception, the methods is not found in that object
VM9231:2944 Uncaught TypeError: data[option] is not a function
    at n.fn.init.$.fn.datepicker (eval at webpackJsonp../node_modules/script-loader/addScript.js.module.exports (scripts.bundle.js:1), <anonymous>:2944:33)
    at <anonymous>:1:36

Actually this is the object stored, and some methods are in __proto__

![image](https://user-images.githubusercontent.com/6633020/26933982-5d873c1e-4c68-11e7-92c6-bddd014c70cc.png)

So I can only hide and show it by doing something like
$(".form-control.staticDateInput").data("ab.datepicker").__proto__.show.call($(".form-control.staticDateInput").data("ab.datepicker"))
or 
$(".form-control.staticDateInput").data("ab.datepicker").__proto__.hide.call($(".form-control.staticDateInput").data("ab.datepicker"))

How can I use that method that was documented to get/set the date from code?

jQuery version: 2.2.4

**Comment by eureka2** [comment]
The getDate method comes with release 2.1.3 of May 7th. Which version do you use?

**Comment by stefanos-tsaklas** [comment]
I downloaded the latest zip and the version is 2.1.1

I now see that the getDate/setDate methods were added May 4th
https://github.com/eureka2/ab-datepicker/commit/015bd1ba0a301fc90889436cf2b3d11a0a2f63a7

and removed on May 6th
https://github.com/eureka2/ab-datepicker/commit/b7a0b30a6680c3be1c1101aa6ce7d79908a63c39

**Comment by eureka2** [comment]
The latest zip contains this :
`
	/**
	 * getDate() is a member function to retrieve the current Datepicker date.
	 * @return the Date object
	 */
	Datepicker.prototype.getDate = function () {
		var val = this.$target.val();
		var date = val === '' ? new Date() :  this.parseDate(val);
		return date;
	} // end getDate()
`

**Comment by stefanos-tsaklas** [comment]
I see, it works now, maybe we had got the zip from another source
(but the version at the top is v2.1.1)

Thanks a lot!
