### ISSUE TITLE
Onload issue - Calender is showing for a fraction of seconds in the time of loading

### ISSUE THREAD

**Issue by priyasm** [eureka2/ab-datepicker#15]

**Comment by dadoadk** [comment]
any solutions for this issue? I'm having the same problem.

**Comment by eureka2** [comment]
I can not reproduce this issue!
Can you give me other indications?
How do you use this component?

**Comment by dadoadk** [comment]
I'm working on a SPA (Single Page Application) so the html is dynamically changed and DOM is rendered as the pages are changing.  So here is an example: As the user opens the page with the date input, the date picker briefly flickers, displays the whole calendar for a split of a second. Slow enough to be caught by naked eye. 

So I tried to hide it with CSS

`div.datepicker-calendar {
    display:none;
}`

and this worked. 

So now when the user opens page with date picker the flickering does not occur.
