### ISSUE TITLE
how can I change the input and out format to  MMM d, yyyy

### ISSUE THREAD

**Issue by mma183** [eureka2/ab-datepicker#16]
set 
outputFormat: MMM d, yyyyt,
inputFormat: ["MMM d, yyyy"],

first time select a day no error. but re-select a day got the following error:
Cannot read property 'month_names_abbreviated' of undefined

any advise. thank you in advance!

**Comment by eureka2** [comment]
Hi,

What's the "t" in the outputFormat ?

**Comment by mma183** [comment]
sorry it's a typo here.  not "t"

outputFormat: MMM d, yyyy,

error:
Uncaught TypeError: Cannot read property 'month_names_abbreviated' of undefined
    at String.<anonymous> (datepicker.js:2482)

**Comment by eureka2** [comment]
Ok, it had a bug that is fixed now, download the latest version and try again

**Comment by mma183** [comment]
looks good to me now. Thanks so much.

**Comment by eureka2** [comment]
you're welcome :)
