### ISSUE TITLE
Remove Focus

### ISSUE THREAD

**Issue by hijoncon** [eureka2/ab-datepicker#2]
Hi. Is there a option to remove the focus in when the page load?

**Comment by eureka2** [comment]
Hi,
No there is no option for this !
Can you explain your need?

**Comment by hijoncon** [comment]
Open up your voice over or jaws is and reload the page. Instead reading to the document from top to bottom, it reads and focus to the input element... Is there a way to do that?

**Comment by srahrich** [comment]
Try this and see if it helps. Remove this from the datepicker.min.js file. 
;this.$target.focus()

**Comment by phanku** [comment]
I ran into this issue also. I used the date picker lower down on the page and upon render the page would display within the middle of the page. 

Why is the focus there at all? Doesn't this break normal user experience? I mean besides loading in the middle of the page doesn't it also break normal tabbing?
I implemented the change above indicated by @srahrich and everything seems to be good.

**Comment by stefanos-tsaklas** [comment]
By removing ;this.$target.focus() breaks the accessibility features implemented by this component,
the focus is set in 14 cases (when the component is constructed, when you select a date, when the popup is opened and you press esc, etc).

You only need to optionally omit focusing when the component is constructed, which may be a problem, e.g. we may have 5 instances of ab-datepicker on our page and the focus is set on the last one.

Please review my pull request for adding a gainFocusOnConstruction option, which by default is true, to be backwards compatible.

**Comment by eureka2** [comment]
The commit of stefanos-tsaklas is merged
Thanks a lot
