### ISSUE TITLE
How to disable datepicker?

### ISSUE THREAD

**Issue by mma183** [eureka2/ab-datepicker#22]
Having trouble disabling the DatePicker here. I am able to disable the input field but the calender glyphicon will still open the picker when click on the calender glyphicon.  

Basically, I want to calender glyphicon is not clickable when disable the input filed.  Is this possible?

**Comment by eureka2** [comment]
With the new version 2.1.7, you can now disable the datepicker like this:
`$('your date selector').datepicker('disable');`

and re-enable it later:
`$('your date selector').datepicker('enable');`
