### ISSUE TITLE
Ctrl+pageUp, Ctrl+pageDown not available in Chrome

### ISSUE THREAD

**Issue by reinrl** [eureka2/ab-datepicker#23]
Unfortunately, Ctrl+pageUp and Ctrl+pageDown are currently in use by Chrome (used for tab by tab navigation), and there is no way to hook into the combination before the browser takes that action. Would Shift+pageUp and Shift+pageDown be a better browser-agnostic solution for navigating a year at a time?

**Comment by eureka2** [comment]
Thank you !
Ctrl+pageUp and Ctrl+pageDown are replaced by Alt+pageUp and Alt+pageDown
