### ISSUE TITLE
Opening Modal View on a Modal

### ISSUE THREAD

**Issue by kirandeep123** [eureka2/ab-datepicker#26]
I tried to open calendar modal view in a popup modal but I am seeing inline view i.e. not able to see close button and modal view in a modal .  

Is it some Issue or do I need to include some attribute ? Please Suggest . 
Please find attached Screenshot which shows date-picker modal in a popup modal .

**Comment by kirandeep123** [comment]
Sorry !! Forget to upload attachment .
Attaching !!

**Comment by kirandeep123** [comment]
Please Find attachment

**Comment by eureka2** [comment]
I do not see the attached screenshot

**Comment by kirandeep123** [comment]
Please Find attached Screenshot

**Comment by kirandeep123** [comment]
Hi ,
I am not able to attach files here by selecting them from my computer . when I hover on ' selecting them' link ,I can see attached file but not able to see when I finally comment .

**Comment by kirandeep123** [comment]
![suggest](https://user-images.githubusercontent.com/31850870/32593025-4bfcbc8c-c54c-11e7-85b2-acde98ca1ac3.png)

**Comment by eureka2** [comment]
Go to http://eureka2.github.io/ab-datepicker/ and click on modal:
![image](https://user-images.githubusercontent.com/200478/32594120-0aabd324-c52b-11e7-9bcd-fbddcf7c6855.png)

The script is then:
```
$(document).ready(function() {
	$('#date').datepicker({
		modal: true,
	});
});
```
![image](https://user-images.githubusercontent.com/200478/32594252-9bfbf520-c52b-11e7-9749-d69bcb418fe9.png)

You can see the close button ....

**Comment by kirandeep123** [comment]
Hi ,
That is Fine .I am using modal attribute and this is working fine in all locations in our application but the issue is when I already have a modal/popover say which is opening in an iframe and I am then implementing datepicker on that modal with this modal attribute set to true its not working and is showing me the same inline view . 

If you have checked the screenshot I attached its a modal which is opening in an iframe and I am trying to open a datepicker modal within that modal .

let me know if you still have questions/concerns/suggestions

**Comment by eureka2** [comment]
I will try to reproduce this issue. Which component do you use for your modal dialog?

**Comment by kirandeep123** [comment]
Hi , 
we are using iframe to open modal dialog and rendering our JSP in that div which contains this frame . 
 You can find code here : 
 <div id="new-modal-div-locked" class="modal-dialog">
			<div class="modal-content">
		      <div class="modal-header">
				  <h2 class="modal-title">
				  
				  </h2>
		      </div>
		      <div id = "new-modal-body-div-locked" class="modal-body">
		      <iframe  id="new-modalframe-locked" aria-labelledby="new-modalframe-locked" width= 100% height="" src="" ></iframe>
			</div>
	      </div>
	  </div>

**Comment by eureka2** [comment]
Ok, but where are the scripts defined? In the page? in the iframe?
Do you use bootstrap modal.js : https://getbootstrap.com/docs/3.3/javascript/#modals ?
Please, give me more elements so that I can test!

Best regards

**Comment by kirandeep123** [comment]
Hi ,
Scripts are defined in the page . No we are not using anything like bootstrap modals . we are just setting modal attribute to true and we are done and this is working as intended on normal pages but issue is with iframe . 

what types of elements are you asking for ?

**Comment by eureka2** [comment]
The title of this issue is 

> Opening Modal View on a Modal

So, there are **two** modal windows. the first is your modal dialog box, the second is the datepicker.

To my knowledge, an iframe or a JSP can not popup  a modal dialog box on the browser, only a Javascript code can do that.

In my opinion, there is a conflict between this Javascript code and the datepicker.

If you do not say what you use as Javascript code to display your modal dialog box, I will not be able to test.

**Comment by eureka2** [comment]
I partially reproduced your dialog box [here](http://eureka2.github.io/ab-datepicker/modal-on-modal.html) and there is no problem

**Comment by kirandeep123** [comment]
Can you share the code or exactly what you used ?

**Comment by eureka2** [comment]
The HTML page:
[modal-on-modal.html.txt](https://github.com/eureka2/ab-datepicker/files/1552077/modal-on-modal.html.txt)

The content of the IFRAME:
[modal-on-modal-iframe.html.txt](https://github.com/eureka2/ab-datepicker/files/1552078/modal-on-modal-iframe.html.txt)

**Comment by kirandeep123** [comment]
If I close main modal without selecting any date after opening datepicker and again open modal from ' add remainder ' button ,datepicker remains open .  

can you please check on this ?

**Comment by eureka2** [comment]
The datepicker does not know that it's in a modal and that this modal has been hidden. It is the responsibility of the app to handle this.

To illustrate, I added this in the iframe code:
```
window.parent.$('#myModal').on('hidden.bs.modal', function (e) {
   $('#send-date').datepicker('hide');
})
```

**Comment by kirandeep123** [comment]
Okay it fixes the problem I guess . 
Thanks for working on this .

**Comment by eureka2** [comment]
You're welcome !
