### ISSUE TITLE
Is there a directive available for AnguarJS?

### ISSUE THREAD

**Issue by dadoadk** [eureka2/ab-datepicker#27]
This datepicker works great with JAWS and other screen readers. Before I get into coding I'd like to ask if anybody already made a directive of this datepicker?

**Comment by eureka2** [comment]
No, sorry ! But your contribution would be welcome, I'm not familiar with AngularJS

**Comment by dadoadk** [comment]
Here it is. 
https://github.com/dadoadk/ng-ab-datepicker

**Comment by eureka2** [comment]
A link to your AngularJS directive has been added to the README.

Thanks a lot
