### ISSUE TITLE
Default date set without being selected, is it possible to close the date picker without setting the date?

### ISSUE THREAD

**Issue by dadoadk** [eureka2/ab-datepicker#28]
What I'm trying to understand is how to either trigger the event when date picker closes, or how to disable the default date selection when the date picker is opened. 

In your demo the input field initially is empty, so when the user clicks on the button the date picker opens and sets the current day as the default date. Is there a way to disable this default date selection?

**Comment by eureka2** [comment]
It's fixed now! Thank you
