### ISSUE TITLE
End date should be greater than start date

### ISSUE THREAD

**Issue by getsetgopi** [eureka2/ab-datepicker#29]
When user selects "today's date" as start date and when selecting the end date, user should not be allowed to select previous date(s). The user should be allowed to select later date.

**Comment by eureka2** [comment]
I think the start and end dates can be the same. An event can begin and end the same day.

If the user selects an end date earlier than the start date, the start date is automatically changed.

This behavior is identical to that of the official bootstrap datepicker: [Try it.](https://uxsolutions.github.io/bootstrap-datepicker/?markup=range&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=4&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox)

**Comment by getsetgopi** [comment]
I agree with you and it works perfect. However, I'm looking for an option to disable the previous dates (excluding the current date) from the end date.

**Comment by eureka2** [comment]
I added the 'allowSameDate' option. If this option is used in conjunction with the 'next' option and contains the value 'false', it will no longer be possible to select the start date as the end date.

```
$('#startdate').datepicker({
	allowSameDate: false,
	next: '#enddate'
});
$('#enddate').datepicker({
	allowSameDate: false,
	previous: '#startdate'
});
```

**Comment by eureka2** [comment]
No reaction so I close this issue!
