### ISSUE TITLE
Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by quikbeam** [eureka2/ab-datepicker#3]
Getting the following error when clicking on the calendar icon:  datepicker.js:2059 Uncaught TypeError: Cannot read property 'top' of undefined

Using jQuery 2.1.4 and Bootstrap 3.0.3

**Comment by quikbeam** [comment]
I resolved the issue by adding a <label> element as seen on the demo page.  Seems that the <label> element is required.

**Comment by Nsrose** [comment]
What element did you add? I tried enclosing the input in the 

`<div class="input-group">...</div>`

but I'm getting the same error
