### ISSUE TITLE
TypeError: Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by zahranoorcs** [eureka2/ab-datepicker#34]
Hi,
 I am trying to use this date-picker because this one is accessible. But i am getting this error : 
**_TypeError: Cannot read property 'top' of undefined_**

I have included all the dependencies. Please let me know if you can help me in this. 

Thanks,
Zahra

**Comment by EmilySamantha80** [comment]
I get this as well, using Bootstrap 4

**Comment by zahranoorcs** [comment]
Thanks for your reply. I will give it a try.
