### ISSUE TITLE
Bootstrap theme incorrect min-width

### ISSUE THREAD

**Issue by maddya** [eureka2/ab-datepicker#37]
When the bootstrap theme is used, the min-width style that's applied to the element (rendering as 160px for me) is too small.

![cal](https://user-images.githubusercontent.com/14932313/44751604-799ab600-aacd-11e8-9241-b2c04ee26d7b.PNG)

![cal2](https://user-images.githubusercontent.com/14932313/44751704-c4b4c900-aacd-11e8-9052-61f61e64b445.PNG)

**Comment by eureka2** [comment]
Fixed : change to 200px of the min-width property for the bootstrap theme
