### ISSUE TITLE
Calendar loses focus when switching months with Pg Up and Pg Down keyboard controls

### ISSUE THREAD

**Issue by maddya** [eureka2/ab-datepicker#38]
When the 31st of a month is selected, and then Pg Up or Pg Down is used to navigate to the previous or following month, the calendar loses focus (but remains expanded) and the keyboard controls stop working.

![image](https://user-images.githubusercontent.com/14932313/45173707-d547fc00-b1bd-11e8-891b-adeb0f8e7d58.png)

![image](https://user-images.githubusercontent.com/14932313/45174369-8bf8ac00-b1bf-11e8-85b6-d7eafcdf0a4c.png)

**Comment by eureka2** [comment]
Fixed in release 2.1.10
