### ISSUE TITLE
Events not working

### ISSUE THREAD

**Issue by theskyliner** [eureka2/ab-datepicker#42]
Hey there,

trying to implement custom color scheme for the datepicker, so I have to loop through all visible and enabled dates in order to assign css classes.

Tried to use the events opening and opened, but they don't seem to work.
I tried to do it like this:
```js
$('#date').on('ab.datepicker.opening', function (datepicker) {
    console.log(datepicker);
});
```

Is this wrong? I don't get any errors it just does not execute.

Thanks in advance.
Best regards
Nick

**Comment by eureka2** [comment]
Hi,

The ab.datepicker.opening and ab.datepicker.opened events are triggered on the **calendar portion** of the date picker

Best regards

**Comment by eureka2** [comment]
Try this:

```
$('.datepicker-calendar').on('ab.datepicker.opening', function(e, datepicker) {
    if (datepicker == 'date') {
        console.log(datepicker);
    }
});
```

**Comment by SanD-76** [comment]
@eureka2 above solution is not working.
Tried both ways. i am using this as function.
datePicker = function () {
    
    $(".datepicker").datepicker({
        markup: 'bootstrap4',
        inputFormat: ["dd/MM/yyyy"],
        outputFormat: 'dd/MM/yyyy',
        opening: function () {
            alert()
        }
    });

    $('.datepicker').on('ab.datepicker.opening', function () {
        alert('hi')
        var val = $(this).val();
        $(this).attr('title', val);
    });
    
}
