### ISSUE TITLE
 not able to capture ab.datepicker.closed  event

### ISSUE THREAD

**Issue by rakeshy3** [eureka2/ab-datepicker#44]
I want to do some stuff inside ab.datepicker.closed callback method. But it is not triggered.

**Comment by eureka2** [comment]
ab.datepicker.closed is not a callback method. It's an event that is triggered on the **calendar portion** of the datepicker.

If you want to capture this event, try something like :
$(<your data selector>).parent().find('.datepicker-calendar').on('ab.datepicker.closed', function() {
   // your stuff here
});

**Comment by rakeshy3** [comment]
done
