### ISSUE TITLE
Reinitialize datepicker() without reloading the page

### ISSUE THREAD

**Issue by getsetgopi** [eureka2/ab-datepicker#49]
Is there a way to reinitialize the datepicker() without reloading the page? I want to reinitialize on click of a button.

**Comment by eureka2** [comment]
just empty the contents of the target input. For example, if the ID of the target input is 'date', do :
`$('#date').val('');` when the user clicks on  your button.

**Comment by getsetgopi** [comment]
I have modified the code to include French verbiage. When the html lang changes to Fr on page load, the month and days in the calendar change to French. But there are cases where language switch happens without page reload.
I need to find a way to destroy and re-initialize the datepicker()

**Comment by shoaib-iqbal** [comment]
I want to re-initialize date picker on response of ajax as I am giving dynamic available dates.
Is there a way I can re-initialize datepicker ?
