### ISSUE TITLE
Why can't I find this on npmjs.com?

### ISSUE THREAD

**Issue by cush4x** [eureka2/ab-datepicker#50]
Why can't I find this on npmjs.com?

I see https://github.com/yext/ab-datepicker (peer? fork?)

Thanks.

**Comment by eureka2** [comment]
yes, this package is a fork

I can not publish this original ab-datepicker on npmjs because @yext published it before me

**Comment by eureka2** [comment]
Hi,

This package is published on npmjs.com now !
