### ISSUE TITLE
Can't tab out of the calendar

### ISSUE THREAD

**Issue by jaceuk** [eureka2/ab-datepicker#51]
Hi,

Thanks for a great datepicker :)

I'm using it inline and I can't seem to tab out of the calendar. It seems the only way to tab out of the calendar is if there is another form element on the page otherwise, as a keyboard user, you're trapped

In my case I have 'Back' and 'Continue' buttons sitting under the calendar but it seems impossible to tab out of the calendar to these buttons.

I've managed to replicate this on your demo page by setting it to inline and removing all other input elements and adding a simple link after the calendar.

I hope this make sense and appreciate any help you might be able to offer.

Thanks

**Comment by eureka2** [comment]
Thank you for reporting this issue! Fixed in version 2.1.17

Best regards

**Comment by jaceuk** [comment]
That's great, thank you :)
